version: "3"

services:
  appsmith:
    image: appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "3380:80"
      - "3443:443"
      - "9031:9001"
    volumes:
      - ./stacks:/appsmith-stacks
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  auto_update:
    image: containrrr/watchtower:latest-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Update check interval in seconds.
    command: --interval 300 --label-enable --cleanup

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      - MAILDEV_OUTGOING_USER=loftwah@local.com
      - MAILDEV_OUTGOING_PASS=loftwah
